export const agencyUsersConstants = {
  GET_AGENCY_USERS_SUCCESS: "GET_AGENCY_USERS_SUCCESS",
  GET_AGENCY_USERS_FAIL: "GET_AGENCY_USERS_FAIL",

  GET_AGENCY_USER_SUCCESS: "GET_AGENCY_USER_SUCCESS",
  GET_AGENCY_USER_FAIL: "GET_AGENCY_USER_FAIL",

  ADD_AGENCY_USER_SUCCESS: "ADD_AGENCY_USER_SUCCESS",
  ADD_AGENCY_USER_FAIL: "ADD_AGENCY_USER_FAIL",

  EDIT_AGENCY_USER_SUCCESS: "EDIT_AGENCY_USER_SUCCESS",
  EDIT_AGENCY_USER_FAIL: "EDIT_AGENCY_USER_FAIL",

  DELETE_AGENCY_USER_SUCCESS: "DELETE_AGENCY_USER_SUCCESS",
  DELETE_AGENCY_USER_FAIL: "DELETE_AGENCY_USER_FAIL",
};
