export const clientsConstants = {
  GET_CLIENTS_SUCCESS: "GET_CLIENTS_SUCCESS",
  GET_CLIENTS_FAIL: "GET_CLIENTS_FAIL",

  GET_CLIENT_SUCCESS: "GET_CLIENT_SUCCESS",
  GET_CLIENT_FAIL: "GET_CLIENT_FAIL",

  ADD_CLIENT_SUCCESS: "ADD_CLIENT_SUCCESS",
  ADD_CLIENT_FAIL: "ADD_CLIENT_FAIL",

  EDIT_CLIENT_SUCCESS: "EDIT_CLIENT_SUCCESS",
  EDIT_CLIENT_FAIL: "EDIT_CLIENT_FAIL",

  DELETE_CLIENT_SUCCESS: "DELETE_CLIENT_SUCCESS",
  DELETE_CLIENT_FAIL: "DELETE_CLIENT_FAIL",
};
