export const delegatesConstants = {
  GET_DELEGATES_SUCCESS: "GET_DELEGATES_SUCCESS",
  GET_DELEGATES_FAIL: "GET_DELEGATES_FAIL",

  GET_DELEGATE_SUCCESS: "GET_DELEGATE_SUCCESS",
  GET_DELEGATE_FAIL: "GET_DELEGATE_FAIL",

  ADD_DELEGATE_SUCCESS: "ADD_DELEGATE_SUCCESS",
  ADD_DELEGATE_FAIL: "ADD_DELEGATE_FAIL",

  EDIT_DELEGATE_SUCCESS: "EDIT_DELEGATE_SUCCESS",
  EDIT_DELEGATE_FAIL: "EDIT_DELEGATE_FAIL",

  DELETE_DELEGATE_SUCCESS: "DELETE_DELEGATE_SUCCESS",
  DELETE_DELEGATE_FAIL: "DELETE_DELEGATE_FAIL",
};
