export const deputiesConstants = {
  GET_DEPUTIES_SUCCESS: "GET_DEPUTIES_SUCCESS",
  GET_DEPUTIES_FAIL: "GET_DEPUTIES_FAIL",

  GET_DEPUTY_SUCCESS: "GET_DEPUTY_SUCCESS",
  GET_DEPUTY_FAIL: "GET_DEPUTY_FAIL",

  ADD_DEPUTY_SUCCESS: "ADD_DEPUTY_SUCCESS",
  ADD_DEPUTY_FAIL: "ADD_DEPUTY_FAIL",

  EDIT_DEPUTY_SUCCESS: "EDIT_DEPUTY_SUCCESS",
  EDIT_DEPUTY_FAIL: "EDIT_DEPUTY_FAIL",

  DELETE_DEPUTY_SUCCESS: "DELETE_DEPUTY_SUCCESS",
  DELETE_DEPUTY_FAIL: "DELETE_DEPUTY_FAIL",
};
