export const referencesConstants = {
  GET_REFERENCES_SUCCESS: "GET_REFERENCES_SUCCESS",
  GET_REFERENCES_FAIL: "GET_REFERENCES_FAIL",

  GET_REFERENCE_SUCCESS: "GET_REFERENCE_SUCCESS",
  GET_REFERENCE_FAIL: "GET_REFERENCE_FAIL",

  ADD_REFERENCE_SUCCESS: "ADD_REFERENCE_SUCCESS",
  ADD_REFERENCE_FAIL: "ADD_REFERENCE_FAIL",

  EDIT_REFERENCE_SUCCESS: "EDIT_REFERENCE_SUCCESS",
  EDIT_REFERENCE_FAIL: "EDIT_REFERENCE_FAIL",

  DELETE_REFERENCE_SUCCESS: "DELETE_REFERENCE_SUCCESS",
  DELETE_REFERENCE_FAIL: "DELETE_REFERENCE_FAIL",
};
