export const walletConstants = {
  GET_WALLET_SUCCESS: "GET_WALLET_SUCCESS",
  GET_WALLET_FAIL: "GET_WALLET_FAIL",
  GET_WALLET_ADD_TRANSACTIONS_SUCCESS: "GET_WALLET_ADD_TRANSACTIONS_SUCCESS",
  GET_WALLET_ADD_TRANSACTIONS_FAIL: "GET_WALLET_ADD_TRANSACTIONS_FAIL",
  GET_WALLET_NET_SUCCESS: "GET_WALLET_NET_SUCCESS",
  GET_WALLET_NET_FAIL: "GET_WALLET_NET_FAIL",
  GET_WALLET_DEDUCT_TRANSACTIONS_SUCCESS:
    "GET_WALLET_DEDUCT_TRANSACTIONS_SUCCESS",
  GET_WALLET_DEDUCT_TRANSACTIONS_FAIL: "GET_WALLET_DEDUCT_TRANSACTIONS_FAIL",
  POST_TRANSACTION_SUCCESS: "POST_TRANSACTION_SUCCESS",
  POST_TRANSACTION_FAIL: "POST_TRANSACTION_FAIL",
  DELETE_TRANSACTION_SUCCESS: "DELETE_TRANSACTION_SUCCESS",
  DELETE_TRANSACTION_FAIL: "DELETE_TRANSACTION_FAIL",
};
